### ISSUE TITLE
the horrific mess of the install that Freepbx ends up being can be cleaned up with time

### ISSUE THREAD

**Issue by tm1000** [boxrick/deploy_freepbx#1]
What does "the horrific mess of the install that Freepbx ends up being can be cleaned up with time" specifically mean?

**Comment by chinovelasco** [comment]
Don't know, but any effort to automate/simplify the installation is welcome :)

**Comment by boxrick** [comment]
Apologies here for bad wording, since obviously the software is excellent otherwise I wouldn't be using it! 

I simply meant so many bits of compiling and dependencies, manually creating users and extra unneeded software such as EPEL. Then a whole bunch of random scripts which do different bits, all felt somewhat messy...

**Comment by boxrick** [comment]
Changed poor wording to better reflect my aim.
