### ISSUE TITLE
Small syntax problem in freepbx.yml

### ISSUE THREAD

**Issue by gp54321** [boxrick/deploy_freepbx#2]
I had success with your ansible playbook in installing a Centos 7 container under Ubuntu 16 LTS.
The only real problem is a very minor one: I had to remove a space before 'service' in the "name: Enable freepbx service" section else my ansible version (2.3)  refused to handle it. Python and its whitespaces...

Other than that I added by hand mod_ssl with yum (could be added automatically but probably additional iptables rules could be necessary, I have found so anyway)

a freepbx.ini in /etc/php.d would be nice to avoid a warning in the dashboard with
session.save_path = "/var/lib/php/sessions"
memory_limit = 512M

there is also a problem with codecs, with the Sangoma distro all codecs are included, with your script it's possible in the Freepbx to select codecs but they don't exist in fact, the opus one for example. Maybe it's because the 'free' nature of this codec is disputed.

and there was a nasty problem with the container I had to create it privileged else some rpm installation would fail but that's more an Ubuntu problem.

**Comment by boxrick** [comment]
> I had success with your ansible playbook in installing a Centos 7 container under Ubuntu 16 LTS.
The only real problem is a very minor one: I had to remove a space before 'service' in the "name: Enable freepbx service" section else my ansible version (2.3) refused to handle it. Python and its whitespaces...

Good news about the install! Oddly enough I fixed that top issue and didn't commit it back, but no reason I cannot do that now.

> Other than that I added by hand mod_ssl with yum (could be added automatically but probably additional iptables rules could be necessary, I have found so anyway)

I have added mod_ssl package

> a freepbx.ini in /etc/php.d would be nice to avoid a warning in the dashboard with
session.save_path = "/var/lib/php/sessions"
memory_limit = 512M

Easy change, I have removed the old memory limit. Added this as an adjustable default parameter and created a template for custom php ini options in the suggested location. 

> there is also a problem with codecs, with the Sangoma distro all codecs are included, with your script it's possible in the Freepbx to select codecs but they don't exist in fact, the opus one for example. Maybe it's because the 'free' nature of this codec is disputed.

This installer is mostly made from the install guide, sadly the 'commercial' modules guide was hidden then removed. During the install process if there is any way of fixing or changing this. Manually or otherwise let me know and I am sure we can try and change it. 

> and there was a nasty problem with the container I had to create it privileged else some rpm installation would fail but that's more an Ubuntu problem.

Never tried running this inside an Ubuntu container, but considering the amount of things which are changed and installed during the FreePBX install its not massively surprising. Would be interesting to know what point this happens at. Then we can look into why it happens and look at some workaround. 

I have just pushed a slightly modified version with the above changes, also added a 'tests' folder. This is for feeding into future CI and can also be used for local development. I have placed a VAGRANTFILE within this. Assuming Virtualbox / Ansible and Vagrant are installed it should be a simple case of 'vagrant up' then pointing the local web browser at port 8080 or 4443

**Comment by gp54321** [comment]
After your commit the 3 first troubles are fixed, thanks.

Sorry for the delay but I wrestled with the 'privileged container' problem.
FYI in a *privileged* container, the container root = the host root. If you sudo in the container, you
are root under the host so it matters a lot for security. If your privileged container is hacked
your host is owned as well.

It seems that for a lxc *unprivileged* container under Ubuntu 16.04 LTS setcap is available but it does not work. 
If you try to use it it fails:
touch aa
sudo setcap cap_net_bind_service,cap_sys_boot=+ep aa
Failed to set capabilities on file `aa' (Invalid argument)
this works all right under the host (the physical computer running Ubuntu 16.04) as well as under a *privileged* container.

As I understand it, for a container running a distro like Centos, using RPM breaks when the package includes a suid executable. 

TASK [deploy_freepbx : Upgrade all packages] fatal: [all]: FAILED! => {"changed": true, "failed": true, "msg": "Error unpacking rpm package iputils-20160308-10.el7.x86_64\

The 'unpacking' error message is misleading, unpack has nothing to do with the problem.
After unpacking, RPM calls setxattr (ie using kernel capabilities as was planned for Fedora 15) to set the S bit:

strace:
getuid()                                = 0
capget({_LINUX_CAPABILITY_VERSION_3, 0}, NULL) = 0
lstat("/usr/bin/ping;59d20360", {st_mode=S_IFREG|0755, st_size=66176, ...}) = 0
setxattr("/usr/bin/ping;59d20360", "security.capability", "\0\0\0\2\0000\0\0\0\0\0\0\0\0\0\0\0\0\0", 20, 0) = -1 EPERM (Operation not permitted)

iputils could be worked around freepbx can work without it but unfortunately httpd has the same problem and it can't be skipped else freepbx will not work.

For a container using apt-get (an Ubuntu container) the problem don't exist since apt detects somehow than setcap is not available and falls back to setuid. I have verified that under a unprivileged container (Ubuntu or Centos don't matter) it's possible to chmod +s a file but setcap does not work.
From what I have seen the problem is that namespace daemon is not available in a container.

See:
http://lxc-users.linuxcontainers.narkive.com/IL4g1Y7i/setcap-capabilities
I think that is relevant (not 100% sure - the 'workaround' does not work for me)

Looking at lxc 2.1 changelog
https://insights.ubuntu.com/2017/09/06/lxc-2-1-has-been-released/
I can't say if it is fixed or not.

I have no idea how this works for a lxc Centos container under a Centos computer. Is an unprivileged container even possible with a Centos host? I remember having seen that the Ubuntu guys were talking about the work necessary to have working unprivileged containers - I guess that Canonical want (or wanted  ? things change so fast) very much to have a share of the cloud, maybe for Centos/Redhat the approach differs and lxc is not a big concern. Anyway to check it I would need to learn to use lxc without the Ubuntu crutches. I'm not looking to it. So I don't see any easy workaround at the moment. I hope to come back to it next week.

**Comment by boxrick** [comment]
FYI LXD 2.18 is available now.

https://github.com/torvalds/linux/commit/8db6c34f1dbc8e06aa016a9b829b06902c3e1340 looks like a fix in the upstream kernel. I guess you just need to wait for it to filter down.

I also read you can install the packages using privileged mode then simply revert back after install, assuming you sort permissions properly.

**Comment by gp54321** [comment]
Yes this upstream fix seems just for that - it will not come to a LTS release though (I hope not or Ubuntu has not the same ideas for a long term release as me) so no quick solution.

and yes, it's possible to switch a container to a unprivileged one. 
For the record create a container in privileged mode can be done with something like
lxc init centos7 asterisk -c security.privileged=true
and switching it to an unprivileged mode can be done with
lxc config set asterisk security.privileged false 
(after stopping it of course) 
But getting automatic security updates will be problematic - if Apache has a security bug update will fail.
